### ISSUE TITLE
Ability to maintain file structure

### ISSUE THREAD

**Issue by nikneem** [chris-kruining/translation-tool#2]
I tend to structure my i18n file so the look logical to me. Most tools mess the order of translations up (or make them ordered alphabetically). I would like to have an option where I can choose to either sort translations alphabetically, or maintain the order where I can pick one of the source files as leading

**Comment by chris-kruining** [comment]
the current implementation (almost MVP ready) preserves the order as authored in the source files. Further sorting features will come in the future
